In [2]:
import pandas as pd

# 读取数据-->read_csv
df = pd.read_csv("data/sales_data.csv", usecols=['订单号','产品类别','产品名称','销售数量','单价'])# usecols指定读取的列

# 数据处理
df['销售金额'] = df['销售数量'] * df['单价']
df

# 写入数据-->to_csv --- index=False 表示不保存索引列
df.to_csv("data/sales_data_new.csv", index=False)

In [12]:
# 数据查看 --> head ,   tail ,  info ,  describe , shape , columns
df1 = pd.read_csv("data/sales_data.csv", usecols=['订单号','产品类别','产品名称','销售数量','单价'])# usecols指定读取的列

df1.head(10)# 查看前10行数据
df1.tail(10)# 查看后10行数据
df1.describe()# 查看数据描述,对数值列进行统计 --> count:计数, mean:平均值, std:标准差, min:最小值, 25%:25%分位数, 50%:50%分位数, 75%:75%分位数, max:最大值
df1.info()# 查看数据信息(列名, 非空计数, 数据类型, 占用内存大小)
df1.shape # 查看数据行数和列数
df1.columns # 查看列名

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   订单号     1000 non-null   int64
 1   产品类别    1000 non-null   object
 2   产品名称    1000 non-null   object
 3   销售数量    1000 non-null   int64
 4   单价      1000 non-null   int64
dtypes: int64(3), object(2)
memory usage: 39.2+ KB

Index(['订单号', '产品类别', '产品名称', '销售数量', '单价'], dtype='object')

In [23]:
# 数据选择
df2 = pd.read_csv("data/sales_data.csv", usecols=['订单号','产品类别','产品名称','销售数量','单价'], index_col='订单号')# usecols指定读取的列 ; index_col指定索引列
df2

# 1.选择列
# 1.1单列
df2['产品类别']
df2.产品类别# 也可以这样写,但不推荐

# 1.2多列
df2[['产品类别','产品名称']]


# 2.选择行 - iloc , loc
# 2.1 iloc ---> 基于行号进行选行(不包含结束位置) , 语法: iloc[start:stop:step]
df2.iloc[0:5:1]
df2.iloc[0:5]

# 2.2 loc ---> 基于行索引进行选行(包含结束位置) , 语法: loc[start:stop:step]
df2.loc[6039081663:6075718574]

            产品类别  产品名称  销售数量   单价
订单号
6039081663  家居用品    抱枕     8   62
6706070220  家居用品    枕头     3  268
6227000596    服装    围巾     8  162
6707557512  电子产品    U盘     5  831
5999170184    图书    字典    12  164
6786607411    服装    T恤    13  170
6212936598  家居用品    枕头     8   50
6616314859  电子产品    耳机    12  413
5953335723    服装   牛仔裤    18  103
6379708537    服装    外套    11  417
5868934737  电子产品    键盘     9  985
6256612023    图书    杂志    15   45
6720054627    服装    围巾    12   90
5995226476  家居用品  餐具套装     5  226
6626281506    图书   工具书    15  151
6373002724  电子产品   路由器    10  514
6875000495    食品    糖果     4   43
6128219838  电子产品    鼠标    18  994
6496119837    图书    字帖     4   88
6317267796    服装    T恤     3  437
6075718574    图书    传记     6  165

In [3]:
df3 = pd.read_csv("data/sales_data.csv")

# 配置项,展示所以的数据
# pd.set_option('display.max_rows', None)

# 数据过滤
# 1.获取 销量大于等于10的数据
df3[df3['销售数量'] >= 10]

# 2.获取产品类别为食物 或图书的数据
df3[df3['产品类别'].isin(['食品', '图书'])]

# 3.获取单价在100-200之间的数据 -->between: 两边边界都包含
df3[df3['单价'].between(125,193,inclusive="right")]# inclusive: 设置包含边界 right: 右边界包含在内, left: 左边界包含在内, both: 两边界都包含在内,neither: 两边界都不包含在内

# 4. 获取销售数量 >=8 , 并且单价 >= 100的数据 ---> 多条件(&: 并且, |: 或)
df3[(df3['销售数量'] >= 8) & (df3['单价'] >= 100)] # 多条件要用括号括起来

# 5.获取产品类别为 服装/食品 , 支付方式为微信/支付宝的数据
df3[(df3['产品类别'].isin(['服装', '食品'])) & (df3['支付方式'].isin(['微信支付', '支付宝']))]

            订单号 产品类别 产品名称  销售数量   单价 客户所在城市  支付方式        订单日期
2    6227000596   服装   围巾     8  162     北京  微信支付  2025-06-08
9    6379708537   服装   外套    11  417     上海  微信支付  2025-06-01
16   6875000495   食品   糖果     4   43     厦门  微信支付  2025-06-07
19   6317267796   服装   T恤     3  437     广州  微信支付  2025-06-01
22   6332373262   食品   面包    11   75     武汉  微信支付  2025-06-10
..          ...  ...  ...   ...  ...    ...   ...         ...
974  6411895158   食品   面包    10   60     西安  微信支付  2025-06-09
976  6376555120   服装   卫衣    14  236     苏州  微信支付  2025-06-05
984  6533009996   食品  矿泉水     6   82     南京   支付宝  2025-06-20
988  5857585420   食品  巧克力     5   60     合肥  微信支付  2025-06-22
999  6147947649   服装   外套    10   64     大连  微信支付  2025-06-25

[194 rows x 8 columns]